### ISSUE TITLE
App fails after adding a new endpoint

### ISSUE THREAD

**Issue by tbi88** [Shuffle/openapi-apps#102]
Hi

I have a custom OpenAPI app which was working just fine. This morning I have added an additional action to it. The version got changed from 1.0.0 to 1.1.0. When I active the new version in a workflow, the app fails. Also it would be cool if we could just choose the version of an OpenAPI app in the GUI like with the custom apps.

{"success":false,"reason":"An exception occurred while running this function. See exception for more details and contact support if this persists (support@shuffler.io)","exception":"'Vectra3596be88ff136d1a90ca7e6db7e7c30e' object has no attribute 'prepare_response'"}

Even when I deleted the new action, it still fails. Do you have any idea what could be the cause here?

Also I am wondering regarding the version system of these apps. I would expect, that the version is changing with every change I make. But this seems not to be the case here. Changed it multiple times today, still on version 1.1.0. Can I somehow force a version change?

Currently running version 1.1.0 of Shuffle, maybe the version is coming from that?

Regards tbi88

**Comment by tbi88** [comment]
And here is the app if that helps.

[vectra.yaml.zip](https://github.com/Shuffle/openapi-apps/files/10392397/vectra.yaml.zip)

**Comment by frikky** [comment]
Hey! Could you share the OpenAPI/swagger for it as well? This will help with the code generation problems :)

**Comment by tbi88** [comment]
Not sure if I have that. I have created the app from scratch. Maybe my initial information was somehow misleading regarding this.

**Comment by frikky** [comment]
> Not sure if I have that. I have created the app from scratch. Maybe my initial information was somehow misleading regarding this.

You can download the specification from the /apps screen! When making from scratch, it still becomes exportable :) 

![image](https://user-images.githubusercontent.com/5719530/212297240-66150ff0-93fd-4e82-9751-6ad84a794b4a.png)

**Comment by tbi88** [comment]
Alright, but that is the same file I have already provided (vectra.yaml) as a ZIP file.

**Comment by frikky** [comment]
> Alright, but that is the same file I have already provided (vectra.yaml) as a ZIP file.

My bad, I thought that would be the entire app. Cheers :+1:

**Comment by tbi88** [comment]
> ```
> docker pull frikky/shuffle:app_sdk
> ```

Thank you, that fixed the issue. So this needs to be done after upgrading to a new version? Probably missed it on the worker nodes.

**Comment by frikky** [comment]
> > ```
> > docker pull frikky/shuffle:app_sdk
> > ```
> 
> Thank you, that fixed the issue. So this needs to be done after upgrading to a new version? Probably missed it on the worker nodes.

It's not necessary every time, but we just have it as a general recommendation, as we may have added extra utilities, bugfixes or speedups for apps there

**Comment by tbi88** [comment]
ok good to know. thanks again.
