### ISSUE TITLE
shuffle iris integartion

### ISSUE THREAD

**Issue by anjana-radhakrishnan** [Shuffle/openapi-apps#135]
Hi I'm facing some issue regarding  integration of iris with shuffle, I'm not seeing an proper documentation regarding this also. Kindly help me on this please.
<img width="957" alt="image" src="https://github.com/Shuffle/openapi-apps/assets/111497171/a1cec930-2476-40f8-8bb2-e3d152210253">
<img width="960" alt="image" src="https://github.com/Shuffle/openapi-apps/assets/111497171/28a64854-e63b-4665-8f8b-71ab27f9a659">

**Comment by rajarammohan0203** [comment]
same issue here 
- how to integrate the shuffle + dfir-iris v2 in the workflow for automating the cases?
- can you please guide me on how to do that @frikky

**Comment by Jabeena-Sayyad** [comment]
Hi @anjana-radhakrishnan, did you find any solution for this integration shuffle with IRIS and wazuh to automate case creation?  kindly let me know if you find anything...

can you please guide us on how to resolve and any reference docs available for the same @frikky

**Comment by frikky** [comment]
> Hi @anjana-radhakrishnan, did you find any solution for this integration shuffle with IRIS and wazuh to automate case creation? kindly let me know if you find anything...
> 
> can you please guide us on how to resolve and any reference docs available for the same @frikky

Hey! Thanks for tagging me in here - I've been traveling until now and will try to fix these things over the next week. Will get back to you.

**Comment by xailong** [comment]
Hi,
Same issue here as the other users, trying to integrate IRIS with Shuffle, trying all the possible options but many errors, could be appreciated your help @frikky  :)
Thank you so much

**Comment by anjana-radhakrishnan** [comment]
Did you get any solution to fix these errors? @frikky

**Comment by DavidtheGoliath** [comment]
Hello @rajarammohan0203 @Jabeena-Sayyad @anjana-radhakrishnan @xailong, we did a tutorial for how to get you started on getting an alert from Wazuh to creating a ticket in IRIS. See the below link for a write up on how to do the aforesaid integration in Shuffle. https://medium.com/@nyereredavid7/using-shuffle-soar-to-create-cases-in-dfir-iris-b32b10a8c86f

**Comment by rajarammohan0203** [comment]
Thanks @DavidtheGoliath @frikky
