### ISSUE TITLE
Index search fails in Elasticsearch SIEM app

### ISSUE THREAD

**Issue by shivharsh-singh** [Shuffle/openapi-apps#27]
Hi,

Using the json downloaded from https://shuffler.io/apps/971706758e274c2e4083f2621fb5a6f7, i try to create an application for Elasticsearch SIEM in Shuffle. 

For the starters, my use case is to perform an index search and based in the result, register a case in TheHive.
However, while  executing the Elasticsearch node in shuffle, the POST index search is not completing  and the corresponding container exits with syntax error.  

```
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED          STATUS                      PORTS                                                                            NAMES
9bfa1bdd8857   frikky/shuffle:elasticsearch_agg_1.0.0                "/bin/sh -c 'python …"   18 seconds ago   Exited (1) 16 seconds ago                                                                                    Elasticsearch_Agg_1-0-0_48dd0a59-15fe-49b3-aec8-0b1cf90b77b2_61aad87a-d982-4ef8-9d1b-5597346bc677

root@vmsoar:/home/user/SOAR/Elasticsearch-SIEM# docker logs 9bfa1bdd8857
  File "/app/app.py", line 1171
    %!s(MISSING).run()
    ^
SyntaxError: invalid syntax  
``` 
I guess there is something wrong with the JSON and i am unable to figure that out. 
Could you please help me fix the issue ?

**Comment by frikky** [comment]
Hey! What version of Shuffle are you on? I believe this was a bug that was fixed quite some time back.

Have a look at your docker-compose.yml file here: https://github.com/frikky/Shuffle/blob/e16220423dfa82aa7d274490a3680fda65068c3b/docker-compose.yml#L20

**Comment by shivharsh-singh** [comment]
Hi , 
Thanks for the reply. 
I am using the latest images. 

```
root@vmsoar:/home/user/SOAR/Shuffle# cat docker-compose.yml | grep image
image: ghcr.io/frikky/shuffle-frontend:latest
image: ghcr.io/frikky/shuffle-backend:latest
image: ghcr.io/frikky/shuffle-orborus:latest
image: opensearchproject/opensearch:1.1.0
```

**Comment by frikky** [comment]
Thanks! May be a problem with

**Comment by shivharsh-singh** [comment]
Hi Fred,

Thanks for fixing in the build. 
It works fine after the upgrade.
