### ISSUE TITLE
Issue with the sentinelone open api authentication

### ISSUE THREAD

**Issue by tristandostaler** [Shuffle/openapi-apps#34]
When trying to run an action in the S1 API (https://github.com/Shuffle/openapi-apps/blob/master/sentinelone.yaml), I get the "Authentication Failed" error.
I believe it is because the header needs to be in this format:
Authorization: Token TheToken

Source (line 43): https://github.com/collectivehealth/sentinelone-sdk/blob/master/sentinelone.py

**Comment by frikky** [comment]
We recently found out why - the format that's correct is this:

Authorization: ApiToken TOKEN

We'll be making a way to add a prefix to keys to ensure you don't need to know about both

**Comment by tristandostaler** [comment]
I was going to say that I got it working with the ApiToken :P you were faster

Thanks!

**Comment by frikky** [comment]
Glad to hear!
