### ISSUE TITLE
App documentation holding onto the documentation from a previously viewed app

### ISSUE THREAD

**Issue by m1nk-code** [Shuffle/openapi-apps#74]
When searching for an app then selecting it, then viewing the documentation.

If an app was selected before it, and the documentation was viewed, you will see the documentation from a previously viewed app.

For example, if you search for and select the Sentinelone app then look at the documentation, then do the same and open the Huntress app, you will see the Sentinelone documentation instead of it changing to the Huntress docs :( .

![image](https://user-images.githubusercontent.com/58112539/190501071-9b797e80-8587-40bb-8e50-b06218e03ee7.png)

**Comment by frikky** [comment]
Fixed in next release
